/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as CreateDocumentLayoutRouteImport } from "./routes/create-document/layout"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CreateDocumentIndexRouteImport } from "./routes/create-document/index"

const CreateDocumentLayoutRoute = CreateDocumentLayoutRouteImport.update({
  id: "/create-document",
  path: "/create-document",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDocumentIndexRoute = CreateDocumentIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CreateDocumentLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/create-document": typeof CreateDocumentLayoutRouteWithChildren
  "/create-document/": typeof CreateDocumentIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/create-document": typeof CreateDocumentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/create-document": typeof CreateDocumentLayoutRouteWithChildren
  "/create-document/": typeof CreateDocumentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/create-document" | "/create-document/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/create-document"
  id: "__root__" | "/" | "/create-document" | "/create-document/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateDocumentLayoutRoute: typeof CreateDocumentLayoutRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/create-document": {
      id: "/create-document"
      path: "/create-document"
      fullPath: "/create-document"
      preLoaderRoute: typeof CreateDocumentLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create-document/": {
      id: "/create-document/"
      path: "/"
      fullPath: "/create-document/"
      preLoaderRoute: typeof CreateDocumentIndexRouteImport
      parentRoute: typeof CreateDocumentLayoutRoute
    }
  }
}

interface CreateDocumentLayoutRouteChildren {
  CreateDocumentIndexRoute: typeof CreateDocumentIndexRoute
}

const CreateDocumentLayoutRouteChildren: CreateDocumentLayoutRouteChildren = {
  CreateDocumentIndexRoute: CreateDocumentIndexRoute,
}

const CreateDocumentLayoutRouteWithChildren =
  CreateDocumentLayoutRoute._addFileChildren(CreateDocumentLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateDocumentLayoutRoute: CreateDocumentLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
