/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as GenerateDocxLayoutRouteImport } from "./routes/generate-docx/layout"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as GenerateDocxroutesSingleTemplateIndexRouteImport } from "./routes/generate-docx/(routes)/single-template/index"
import { Route as GenerateDocxroutesMultipleTemplatesIndexRouteImport } from "./routes/generate-docx/(routes)/multiple-templates/index"

const GenerateDocxLayoutRoute = GenerateDocxLayoutRouteImport.update({
  id: "/generate-docx",
  path: "/generate-docx",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateDocxroutesSingleTemplateIndexRoute =
  GenerateDocxroutesSingleTemplateIndexRouteImport.update({
    id: "/(routes)/single-template/",
    path: "/single-template/",
    getParentRoute: () => GenerateDocxLayoutRoute,
  } as any)
const GenerateDocxroutesMultipleTemplatesIndexRoute =
  GenerateDocxroutesMultipleTemplatesIndexRouteImport.update({
    id: "/(routes)/multiple-templates/",
    path: "/multiple-templates/",
    getParentRoute: () => GenerateDocxLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/generate-docx": typeof GenerateDocxLayoutRouteWithChildren
  "/generate-docx/multiple-templates/": typeof GenerateDocxroutesMultipleTemplatesIndexRoute
  "/generate-docx/single-template/": typeof GenerateDocxroutesSingleTemplateIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/generate-docx": typeof GenerateDocxLayoutRouteWithChildren
  "/generate-docx/multiple-templates": typeof GenerateDocxroutesMultipleTemplatesIndexRoute
  "/generate-docx/single-template": typeof GenerateDocxroutesSingleTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/generate-docx": typeof GenerateDocxLayoutRouteWithChildren
  "/generate-docx/(routes)/multiple-templates/": typeof GenerateDocxroutesMultipleTemplatesIndexRoute
  "/generate-docx/(routes)/single-template/": typeof GenerateDocxroutesSingleTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/generate-docx"
    | "/generate-docx/multiple-templates/"
    | "/generate-docx/single-template/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/generate-docx"
    | "/generate-docx/multiple-templates"
    | "/generate-docx/single-template"
  id:
    | "__root__"
    | "/"
    | "/generate-docx"
    | "/generate-docx/(routes)/multiple-templates/"
    | "/generate-docx/(routes)/single-template/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateDocxLayoutRoute: typeof GenerateDocxLayoutRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/generate-docx": {
      id: "/generate-docx"
      path: "/generate-docx"
      fullPath: "/generate-docx"
      preLoaderRoute: typeof GenerateDocxLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/generate-docx/(routes)/single-template/": {
      id: "/generate-docx/(routes)/single-template/"
      path: "/single-template"
      fullPath: "/generate-docx/single-template/"
      preLoaderRoute: typeof GenerateDocxroutesSingleTemplateIndexRouteImport
      parentRoute: typeof GenerateDocxLayoutRoute
    }
    "/generate-docx/(routes)/multiple-templates/": {
      id: "/generate-docx/(routes)/multiple-templates/"
      path: "/multiple-templates"
      fullPath: "/generate-docx/multiple-templates/"
      preLoaderRoute: typeof GenerateDocxroutesMultipleTemplatesIndexRouteImport
      parentRoute: typeof GenerateDocxLayoutRoute
    }
  }
}

interface GenerateDocxLayoutRouteChildren {
  GenerateDocxroutesMultipleTemplatesIndexRoute: typeof GenerateDocxroutesMultipleTemplatesIndexRoute
  GenerateDocxroutesSingleTemplateIndexRoute: typeof GenerateDocxroutesSingleTemplateIndexRoute
}

const GenerateDocxLayoutRouteChildren: GenerateDocxLayoutRouteChildren = {
  GenerateDocxroutesMultipleTemplatesIndexRoute:
    GenerateDocxroutesMultipleTemplatesIndexRoute,
  GenerateDocxroutesSingleTemplateIndexRoute:
    GenerateDocxroutesSingleTemplateIndexRoute,
}

const GenerateDocxLayoutRouteWithChildren =
  GenerateDocxLayoutRoute._addFileChildren(GenerateDocxLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateDocxLayoutRoute: GenerateDocxLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
